[package]
name = "quick-presenter"
version = "1.0.0"
edition = "2021"
license = "GPL-3.0-only"

[[bin]]
name = "quick-presenter"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
notify = "8.2"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rfd = "0.17"
slint = { version = "1.18.1", features = ["raw-window-handle-06"] }
pdfium-render = "=0.9.1"

[build-dependencies]
slint-build = "1.18.1"
winresource = { version = "0.1.31", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", default-features = false, features = [
    "NSImage",
    "NSApplication",
    "NSMenu",
    "NSMenuItem",
    "NSView",
    "NSWindow",
] }
objc2-foundation = { version = "0.3.2", default-features = false, features = [
    "NSObject",
] }
raw-window-handle = "0.6"

[target.'cfg(target_os = "windows")'.dependencies]
raw-window-handle = "0.6"
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_Storage_FileSystem",
] }
